const care = [['01','100% 남성 전담','상담부터 시술, 후케어까지 남성 의료진과 스태프가 함께합니다.'],['02','1인 VIP 프라이빗 룸','시선과 동선을 분리한 독립 공간에서 편안하게 진행합니다.'],['03','1:1 커스텀 파라미터','피부 톤과 모질, 굵기, 모근 깊이에 맞춰 출력을 정밀하게 설정합니다.'],['04','듀얼 컴포트 시스템','표면 마취와 스마트 에어 쿨링을 함께 적용해 통증 부담을 낮춥니다.']];
const areas = [['FACE','수염 · 인중 · 턱 · 목','매일 반복되는 면도 시간과 자극, 푸른 수염 자국을 줄여 보다 단정한 인상으로'],['BODY','가슴 · 배 · 등 · 팔 · 다리','털 박힘과 운동 중 쓸림을 줄여 깔끔하고 쾌적한 바디라인으로'],['PRIVATE','브라질리언 · 음낭 · 회음부 · 항문','땀과 습기로 인한 불편을 줄이고 통풍과 위생 관리는 보다 편리하게']];
const process = ['1:1 정밀 상담','표면 마취','맞춤 레이저 시술','급속 쿨링 & 진정','관리 수칙 안내'];
const prices = [['얼굴','인중 15 · 턱 25 · 목 20 · 볼 20 · 구레나룻 20 · 얼굴전체 50 · 뒷목 헤어라인 25'],['상체','가슴 40 · 배 40 · 가슴+배 75 · 유륜 20 · 허리 35 · 등 75'],['팔','겨드랑이 5 · 어깨 35 · 상완 35 · 하완 35 · 손 20'],['하체','엉덩이 50 · 종아리 100 · 허벅지 100 · 발 20'],['프라이빗','삼각라인 50 · 브라질리언 150 · 성기 50 · 음모 50 · 음낭 80 · 회음부 40 · 항문 40 · 항문+회음부 75']];
const technology = [['4mm','최대 침투 깊이','깊고 굵은 남성 모근까지 에너지가 도달하도록 맞춤 설정'],['24mm','XL 스팟 사이즈','넓은 부위를 빠르고 균일하게 조사할 수 있는 대형 스팟'],['DUAL','755 + 1064nm','피부 톤과 모질에 맞춰 선택하는 알렉산드라이트·엔디야그 파장'],['COOL','SmartCool','레이저 조사 전·중·후 연속 냉각으로 피부 표면을 보호']];
const faqs = [['몇 회 정도 받아야 효과가 나타나나요?','남성 모근은 굵고 재생력이 강해 보통 4~6주 간격으로 5회 이상을 권장합니다. 개인의 모질과 부위에 따라 필요한 횟수는 달라질 수 있습니다.'],['브라질리언 제모가 민망하지 않을까요?','남성 의료진과 스태프가 독립된 1인 룸에서 진행합니다. 프라이버시를 우선한 동선과 편안한 안내로 부담을 덜어드립니다.'],['남성 수술 전후에도 가능한가요?','가능합니다. 다만 수술 후에는 회복 상태에 따라 일정 조율이 필요하므로 전문의 상담 후 진행합니다.'],['화상이나 모낭염이 걱정됩니다.','피부와 모근 상태에 맞춘 출력, 연속 에어 쿨링, 시술 후 진정 처치로 위험을 낮춥니다. 모든 시술에는 개인차와 부작용 가능성이 있어 사전 상담이 필요합니다.']];

export default function Home(){return <main>
  <nav className="nav"><a href="#top" className="brand" aria-label="JJ 남성제모 홈"><b>JJ</b><span>MEN'S CLINIC</span></a><div className="navLinks"><a href="#why">WHY JJ</a><a href="#technology">TECHNOLOGY</a><a href="#program">PROGRAM</a><a href="#price">PRICE</a></div><a className="navCta" href="#consultation">상담 예약</a></nav>
  <section className="hero" id="top"><div className="heroGlow"/><div className="eyebrow">JJ MALE GROOMING PROTOCOL</div><h1>남성 제모,<br/><em>남성을 이해하는 곳에서.</em></h1><p>굵고 깊은 모근부터 민감한 프라이빗 부위까지.<br className="desktop"/> 남성의 피부와 신체 구조를 고려한 맞춤 레이저 제모</p><div className="heroActions"><a className="primary" href="#consultation">1:1 비밀 상담</a><a className="textLink" href="#why">JJ 제모 알아보기 <span>↘</span></a></div><div className="heroStats"><div><strong>100%</strong><span>남성 의료진·스태프</span></div><div><strong>1:1</strong><span>피부·모질 맞춤 출력</span></div><div><strong>PRIVATE</strong><span>독립된 시술 공간</span></div></div><div className="visualPlaceholder" aria-label="추후 대표 이미지가 들어갈 영역"><span>IMAGE AREA · 사진 교체 예정</span></div></section>
  <section className="manifesto"><span>WHY UROLOGY?</span><h2>남성의 굵고 깊은 털은<br/>다른 접근이 필요합니다.</h2><p>남성 체모는 모근이 깊고 밀도가 높으며 호르몬의 영향을 강하게 받습니다. 높은 출력이 필요한 만큼 피부 상태와 신체 구조를 세심하게 살피고, 부위별 모근 깊이와 모질에 맞춘 계획이 중요합니다.</p></section>
  <section className="care section" id="why"><div className="sectionHead"><span>PRIVATE CARE</span><h2>망설였던 이유까지<br/>케어의 기준으로.</h2></div><div className="careGrid">{care.map(([num,title,text])=><article key={num}><b>{num}</b><h3>{title}</h3><p>{text}</p></article>)}</div></section>
  <section className="equipment section" id="technology"><div className="equipmentVisual"><div className="orb"/><span>APOGEE<br/>ELITE+</span><small>실제 장비 이미지 교체 예정</small></div><div className="equipmentCopy"><span>FDA CLEARED LASER SYSTEM</span><h2>깊고 굵은 털을 위한<br/>두 개의 정밀한 파장.</h2><p>사이노슈어 아포지 엘리트 플러스의 755nm 알렉산드라이트와 1064nm 롱펄스 엔디야그를 피부 톤과 모질에 맞춰 선택합니다.</p><ul><li><b>24mm XL SPOT</b> 넓은 면적을 빠르고 균일하게 조사</li><li><b>SMART COOL</b> 조사 전·중·후 연속 에어 쿨링</li><li><b>NON-CONTACT</b> 젤을 바르지 않는 비접촉 방식</li></ul></div></section>
  <section className="techFacts section">{technology.map(([value,title,text])=><article key={title}><strong>{value}</strong><h3>{title}</h3><p>{text}</p></article>)}</section>
  <section className="areas section" id="program"><div className="sectionHead"><span>PROGRAM</span><h2>보이는 곳부터<br/>말하기 어려운 곳까지.</h2></div><div className="areaGrid">{areas.map(([label,title,text],i)=><article key={label}><span>{label}</span><div className={`abstract a${i+1}`}><i/><b>이미지 준비 중</b></div><h3>{title}</h3><p>{text}</p></article>)}</div></section>
  <section className="process section"><div className="sectionHead"><span>5-STEP PROCESS</span><h2>상담부터 진정까지<br/>남성 맞춤 5단계.</h2></div><ol>{process.map((item,i)=><li key={item}><span>0{i+1}</span><b>{item}</b><small>{['피부 타입·털 밀도·굵기·희망 라인을 확인합니다.','부위와 통증 민감도에 따라 표면 마취 후 충분히 기다립니다.','모근 깊이와 피부 반응에 맞춰 파장과 출력을 설정합니다.','레이저 열감을 낮추고 피부를 편안하게 진정시킵니다.','모낭염 예방과 일상 관리 방법을 자세히 안내합니다.'][i]}</small></li>)}</ol></section>
  <section className="price section" id="price"><div className="sectionHead"><span>PRICE GUIDE</span><h2>시술 부위별 비용 안내</h2><p>표기 금액 단위: 만원 · 개인 상태와 시술 범위에 따라 달라질 수 있습니다.</p></div><div className="priceList">{prices.map(([area,items])=><div key={area}><b>{area}</b><span>{items}</span><a href="#consultation">상담하기 →</a></div>)}</div></section>
  <section className="precare section"><div><span>PRE-CARE</span><h3>시술 전</h3><p>시술 1~2일 전 면도기로 가볍게 면도해 주세요. 털을 뽑거나 왁싱하면 레이저가 목표로 하는 모근이 사라질 수 있습니다. 최소 2주간 선탠과 과도한 야외 활동도 피해주세요.</p></div><div><span>POST-CARE</span><h3>시술 후</h3><p>당일 미온수 샤워는 가능하며 3~5일간 사우나·찜질방·격한 운동을 피해주세요. 노출 부위에는 자외선 차단제를 꼼꼼히 사용하고 이상 반응이 지속되면 의료진에게 문의하세요.</p></div></section>
  <section className="faq section"><div className="sectionHead"><span>FAQ</span><h2>자주 묻는 질문</h2></div><div>{faqs.map(([q,a],i)=><details key={q}><summary><span>0{i+1}</span>{q}<b>＋</b></summary><p>{a}</p></details>)}</div></section>
  <section className="consultation" id="consultation"><span>PRIVATE CONSULTATION</span><h2>제모는 단순히 털을 없애는 것이 아니라,<br/><em>남성을 위한 관리의 시작입니다.</em></h2><p>원하는 부위와 현재 피부 상태를 알려주세요. 남성 전담 스태프가 부담 없이 안내해 드립니다.</p><div className="contactActions"><a className="kakao" href="https://pf.kakao.com/_qYlyV" target="_blank" rel="noreferrer">카카오톡 1:1 상담 <span>↗</span></a><a className="phone" href="tel:1599-5952">전화 상담 1599-5952</a></div><div className="clinicInfo"><span>서울 강남구 선릉로 815, 신한양빌딩</span><span>수인분당선 압구정로데오역 5번 출구</span></div></section>
  <footer><div className="brand"><b>JJ</b><span>MEN'S CLINIC</span></div><p>본 페이지는 시술 이해를 돕기 위한 일반적인 안내입니다. 시술 효과와 통증, 회복 및 부작용에는 개인차가 있으며 정확한 계획은 의료진 상담 후 결정됩니다.</p><span>© JJ UROLOGY. ALL RIGHTS RESERVED.</span></footer>
</main>}
