const care = [['01','100% 남성 전담','상담부터 시술, 후케어까지 남성 의료진과 스태프가 함께합니다.'],['02','1인 VIP 프라이빗 룸','시선과 동선을 분리한 독립 공간에서 편안하게 진행합니다.'],['03','1:1 커스텀 파라미터','피부 톤과 모질, 굵기, 모근 깊이에 맞춰 출력을 정밀하게 설정합니다.'],['04','듀얼 컴포트 시스템','표면 마취와 스마트 에어 쿨링을 함께 적용해 통증 부담을 낮춥니다.']];
const areas = [['FACE','수염 · 인중 · 턱 · 목','반복되는 면도 자극과 푸른 자국을 줄여 더 단정한 인상으로'],['BODY','가슴 · 배 · 등 · 팔 · 다리','쓸림과 털 박힘을 줄여 쾌적하고 깔끔한 바디라인으로'],['PRIVATE','브라질리언 · 회음부 · 항문','통풍과 청결을 높이고 운동 중 불편함은 줄이도록']];
const process = ['1:1 정밀 상담','표면 마취','맞춤 레이저 시술','급속 쿨링 & 진정','관리 수칙 안내'];
const prices = [['얼굴','인중 15 · 턱 25 · 목 20 · 얼굴전체 50'],['상체','가슴 40 · 배 40 · 가슴+배 75 · 등 75'],['팔','겨드랑이 5 · 상완 35 · 하완 35 · 어깨 35'],['하체','종아리 100 · 허벅지 100 · 엉덩이 50'],['프라이빗','브라질리언 150 · 음낭 80 · 성기 50 · 항문 40']];
const faqs = [['몇 회 정도 받아야 효과가 나타나나요?','남성 모근은 굵고 재생력이 강해 보통 4~6주 간격으로 5회 이상을 권장합니다. 개인의 모질과 부위에 따라 필요한 횟수는 달라질 수 있습니다.'],['브라질리언 제모가 민망하지 않을까요?','남성 의료진과 스태프가 독립된 1인 룸에서 진행합니다. 프라이버시를 우선한 동선과 편안한 안내로 부담을 덜어드립니다.'],['남성 수술 전후에도 가능한가요?','가능합니다. 다만 수술 후에는 회복 상태에 따라 일정 조율이 필요하므로 전문의 상담 후 진행합니다.'],['화상이나 모낭염이 걱정됩니다.','피부와 모근 상태에 맞춘 출력, 연속 에어 쿨링, 시술 후 진정 처치로 위험을 낮춥니다. 모든 시술에는 개인차와 부작용 가능성이 있어 사전 상담이 필요합니다.']];

export default function Home(){return <main>
  <nav className="nav"><a href="#top" className="brand" aria-label="JJ 남성제모 홈"><b>JJ</b><span>MEN'S CLINIC</span></a><div className="navLinks"><a href="#why">WHY JJ</a><a href="#program">PROGRAM</a><a href="#price">PRICE</a></div><a className="navCta" href="#consultation">상담 예약</a></nav>
  <section className="hero" id="top"><div className="heroGlow"/><div className="eyebrow">JJ MALE GROOMING PROTOCOL</div><h1>남자의 피부는<br/><em>다르게 다뤄야 하니까.</em></h1><p>굵고 깊은 남성 체모를 이해하는 비뇨의학과 전문의의<br className="desktop"/> 정밀한 남성 맞춤 레이저 제모</p><div className="heroActions"><a className="primary" href="#consultation">프라이빗 상담 예약</a><a className="textLink" href="#why">프로그램 알아보기 <span>↘</span></a></div><div className="heroStats"><div><strong>100%</strong><span>남성 전담 의료진</span></div><div><strong>1:1</strong><span>개인 맞춤 파라미터</span></div><div><strong>2 WAVE</strong><span>듀얼 파장 시스템</span></div></div><div className="visualPlaceholder" aria-label="추후 대표 이미지가 들어갈 영역"><span>IMAGE AREA</span></div></section>
  <section className="manifesto"><span>WHY UROLOGY?</span><h2>더 높은 에너지가 필요한 만큼,<br/>더 섬세한 이해가 필요합니다.</h2><p>남성의 체모는 모근이 깊고 밀도가 높으며 남성 호르몬의 영향을 강하게 받습니다. JJ는 남성의 해부학적 구조와 피부 특성을 바탕으로 효과와 안전을 함께 설계합니다.</p></section>
  <section className="care section" id="why"><div className="sectionHead"><span>PRIVATE CARE</span><h2>망설였던 이유까지<br/>케어의 기준으로.</h2></div><div className="careGrid">{care.map(([num,title,text])=><article key={num}><b>{num}</b><h3>{title}</h3><p>{text}</p></article>)}</div></section>
  <section className="equipment section"><div className="equipmentVisual"><div className="orb"/><span>APOGEE<br/>ELITE+</span><small>장비 이미지 영역</small></div><div className="equipmentCopy"><span>HIGH-END LASER SYSTEM</span><h2>깊고 굵은 털을 위한<br/>두 개의 정밀한 파장.</h2><p>755nm 알렉산드라이트와 1064nm 롱펄스 엔디야그의 듀얼 파장으로 얇은 잔털부터 깊은 모근까지 선택적으로 접근합니다.</p><ul><li><b>24mm XL SPOT</b> 넓은 부위도 빠르고 균일하게</li><li><b>SMART COOL</b> 시술 전·중·후 연속 에어 쿨링</li><li><b>NON-CONTACT</b> 젤 없이 쾌적한 비접촉 시술</li></ul></div></section>
  <section className="areas section" id="program"><div className="sectionHead"><span>PROGRAM</span><h2>보이는 곳부터<br/>말하기 어려운 곳까지.</h2></div><div className="areaGrid">{areas.map(([label,title,text],i)=><article key={label}><span>{label}</span><div className={`abstract a${i+1}`}><i/><b>이미지 준비 중</b></div><h3>{title}</h3><p>{text}</p></article>)}</div></section>
  <section className="process section"><div className="sectionHead"><span>5-STEP PROCESS</span><h2>처음부터 마지막까지<br/>흐트러짐 없는 과정.</h2></div><ol>{process.map((item,i)=><li key={item}><span>0{i+1}</span><b>{item}</b></li>)}</ol></section>
  <section className="price section" id="price"><div className="sectionHead"><span>PRICE GUIDE</span><h2>시술 부위별 비용 안내</h2><p>표기 금액 단위: 만원 · 개인 상태와 시술 범위에 따라 달라질 수 있습니다.</p></div><div className="priceList">{prices.map(([area,items])=><div key={area}><b>{area}</b><span>{items}</span><a href="#consultation">상담하기 →</a></div>)}</div></section>
  <section className="precare section"><div><span>PRE-CARE</span><h3>시술 전</h3><p>1~2일 전 면도기로 가볍게 면도해 주세요. 왁싱이나 털 뽑기는 피하고, 최소 2주간 과도한 태닝을 삼가 주세요.</p></div><div><span>POST-CARE</span><h3>시술 후</h3><p>당일 미온수 샤워는 가능하며, 3~5일간 사우나·찜질방·격한 운동을 피하고 노출 부위에는 자외선 차단제를 사용해 주세요.</p></div></section>
  <section className="faq section"><div className="sectionHead"><span>FAQ</span><h2>자주 묻는 질문</h2></div><div>{faqs.map(([q,a],i)=><details key={q}><summary><span>0{i+1}</span>{q}<b>＋</b></summary><p>{a}</p></details>)}</div></section>
  <section className="consultation" id="consultation"><span>PRIVATE CONSULTATION</span><h2>제모는 털을 없애는 것이 아니라,<br/><em>남성을 위한 관리의 시작입니다.</em></h2><p>부담 없이 고민을 남겨주세요. 필요한 부위와 피부 상태에 맞춰 안내해 드립니다.</p><a href="https://jj-man.co.kr/child/sub/landing/" target="_blank" rel="noreferrer">온라인 상담 바로가기 <span>↗</span></a></section>
  <footer><div className="brand"><b>JJ</b><span>MEN'S CLINIC</span></div><p>본 페이지는 시술 이해를 돕기 위한 안내이며, 시술 효과와 회복에는 개인차가 있습니다. 정확한 내용은 의료진 상담을 통해 확인해 주세요.</p><span>© JJ UROLOGY. ALL RIGHTS RESERVED.</span></footer>
</main>}
